In [ ]:
#sensitivity analysis function

In [10]:
import numpy as np
import pandas as pd
%run blackscholes.ipynb

In [40]:
#S = asset price
#K = strike price
#T = expiration time (yrs)
#r = risk free rate (annualized)
#sig = volatility

def sensitivityAnalysis(option):

    optionData = {'Asset-Price': option.S, 
                  'Strike-Price': option.K, 
                  'Expiration-(yrs)': option.T, 
                  'Risk-Free-Rate': option.r, 
                  'Volatility': option.sig}

    testrange = list(range(-30,30,5))
    df = pd.DataFrame()

    for key in optionData.keys():
        print(key)
        tempOption = optionData.copy()
        for index,var in enumerate(testrange):

            tempOption[key] = optionData[key] * (1+var/100)
            
            option.S = tempOption['Asset-Price']
            option.K = tempOption['Strike-Price']
            option.T = tempOption['Expiration-(yrs)']
            option.r = tempOption['Risk-Free-Rate']
            option.sig = tempOption['Volatility']

            print(option.calcPrice())
            
            df.loc[index,'Price'] = option.calcPrice()

    return df

In [41]:
testEC = EuropeanCall(100,110,5,.05,.1)
sensitivityAnalysis(testEC)

Asset-Price
-6.355772301661133
-2.4098462508847405
1.5360797998916524
5.482005850668045
9.427931901444438
13.373857952220831
17.319784002997224
21.265710053773617
25.211636104550024
29.15756215532639
33.103488206102796
37.04941425687919
Strike-Price
35.7994051067564
32.71946825612987
29.63953140550334
26.55959455487681
23.479657704250272
20.399720853623748
17.319784002997224
14.239847152370686
11.159910301744148
8.079973451117638
5.0000366004911
1.920099749864562
Expiration-(yrs)
12.522218675210539
13.34700678935053
14.161549220986402
14.965973244030295
15.760404551372403
16.544967274520815
17.319784002997224
18.0849758034918
18.840662238780197
19.586961386405378
20.323989857127508
21.051862813144638
Risk-Free-Rate
12.522218675210539
13.34700678935053
14.161549220986402
14.965973244030295
15.760404551372403
16.544967274520815
17.319784002997224
18.0849758034918
18.840662238780197
19.586961386405378
20.323989857127508
21.051862813144638
Volatility
17.319784002997224
17.319784002997224
17.319784002997224
17.319784002997224
17.319784002997224
17.319784002997224
17.319784002997224
17.319784002997224
17.319784002997224
17.319784002997224
17.319784002997224
17.319784002997224

        Price
0   17.319784
1   17.319784
2   17.319784
3   17.319784
4   17.319784
5   17.319784
6   17.319784
7   17.319784
8   17.319784
9   17.319784
10  17.319784
11  17.319784